SIGT-TFI/Controllers/ObraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BLL;
using PagedList;
using PagedList.Mvc;

namespace SIGT_TFI.Controllers
{
    public class ObraController : Controller
    {
        // GET: Obra
        [Authorize]
        public ActionResult Index(int id, string search, int? page)
        {
            var cp = new BLLObra();
            var lista = cp.ListByCompanyID(id);
            if (search == null) search = "";
            return View(lista.Where(x => x.Nombre.ToUpper().StartsWith(search.ToUpper())).ToList().ToPagedList(page ?? 1, 10));
        }

        // GET: Obra/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contacto/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            var obra = new Obra();
            obra.IdCliente = id;

            return View(obra);
        }

        // POST: Contacto/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Obra obra, int id)
        {

            BLLObra bll = new BLLObra();
            obra.IdCliente = id;
            obra.id = 0;

            bll.CreateObra(obra);
            return RedirectToAction("Index", new { id = id });
        }

        // GET: Obra/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Obra/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Obra/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Obra/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Controllers/RecorridoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using Entities;
using BLL;

namespace SIGT_TFI.Controllers
{
    public class RecorridoController : Controller
    {
        // GET: Recorrido
        [Authorize]
        public ActionResult Index(int id, string search, int? page)
        {
            var cp = new BLLRecorrido();
            var lista = cp.ListByObra(id);
            if (search == null) search = "";
            return View(lista.Where(x => x.Inicio.ToUpper().StartsWith(search.ToUpper())).ToList().ToPagedList(page ?? 1, 10));
        }

        // GET: Recorrido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contacto/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            var recorrido = new Recorrido();
            recorrido.IdObra = id;

            return View(recorrido);
        }

        // POST: Contacto/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Recorrido recorrido, int id)
        {

            BLLRecorrido bll = new BLLRecorrido();
            recorrido.IdObra = id;
            recorrido.id = 0;

            bll.CreateRecorrido(recorrido);
            return RedirectToAction("Index", new { id = recorrido.IdObra });
        }

        // GET: Recorrido/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Recorrido/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recorrido/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Recorrido/Delete/5
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Views/Recorrido/Create.cshtml
@model Entities.Recorrido

@{
    ViewBag.Title = "Create";
    var id = Url.RequestContext.RouteData.Values["id"];
}

<h2>@SIGT_TFI.Resources.HomeTexts.Recorrido</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@SIGT_TFI.Resources.HomeTexts.Recorrido</h4>
        <hr />
        
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, @SIGT_TFI.Resources.HomeTexts.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Inicio, @SIGT_TFI.Resources.HomeTexts.Inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Inicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fin, @SIGT_TFI.Resources.HomeTexts.Fin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@SIGT_TFI.Resources.HomeTexts.Crear" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
   @Html.ActionLink("Back to List", "Index", new { id })
</div>

SIGT-TFI/Views/Recorrido/Index.cshtml
@model IEnumerable<Entities.Recorrido>

@{
    ViewBag.Title = "Index";
    var id = Url.RequestContext.RouteData.Values["id"];
}

<h2>@SIGT_TFI.Resources.HomeTexts.listrecorridosporobra</h2>

<p>
    @Html.ActionLink(@SIGT_TFI.Resources.HomeTexts.Recorridos, "Create", new { id }, new { @class = "btn btn-primary btn-large" })
</p>
<table class="table">
    <tr>
        <th>
            @SIGT_TFI.Resources.HomeTexts.Nombre
        </th>
        <th>
            @SIGT_TFI.Resources.HomeTexts.FechaiTraslado
        </th>
        <th>
            @SIGT_TFI.Resources.HomeTexts.FechafTraslado
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Inicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fin)
        </td>
        
    </tr>
}



</table>

<div>
    @Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Volver, "Index", "Obra", new { id }, null)
</div>