SIGT-TFI/Controllers/BitacoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BLL;
using PagedList;
using PagedList.Mvc;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;

namespace SIGT_TFI.Controllers
{
    public class BitacoraController : Controller
    {
        // GET: Bitacora
        [Authorize]
        public ActionResult Index(string search, int? page)
        {
            var cp = new BLLBitacoraSQL();
            var lista = cp.LISTAR_Bitacora();
            if (search == null) search = "";
            return View(lista.Where(x => x.tipo.ToUpper().StartsWith(search.ToUpper())).ToList().ToPagedList(page ?? 1, 10));

        }

        // GET: Bitacora/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Bitacora/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bitacora/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bitacora/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Bitacora/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bitacora/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Bitacora/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BLL;
using PagedList;
using PagedList.Mvc;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using ClosedXML.Excel;

namespace SIGT_TFI.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Empresa
        [Authorize]
        public ActionResult Index(string search, int? page)
        {
            var cp = new BLLEmpresa();
            var lista = cp.AllCliente();
            var btc = new BLLTipoContribuyente();
            ViewData["TipoContribuyente"] = btc.All();
            if (search == null) search = "";
            return View(lista.Where(x => x.RazonSocial.ToUpper().StartsWith(search.ToUpper())).ToList().ToPagedList(page ?? 1, 10));

        }
        [Authorize]

        public ActionResult ExportToExcel(string search, int? page)
        {
            var gv = new GridView();
            var cp = new BLLEmpresa();
            var lista = cp.AllCliente();
            gv.DataSource = cp.AllCliente();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View(lista.Where(x => x.RazonSocial.ToUpper().StartsWith(search.ToUpper())).ToList().ToPagedList(page ?? 1, 10));
        }

        // GET: Empresa/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize]
        // GET: Empresa/Create
        public ActionResult Create()
        {
            var be = new BLLEmpresa();
            var bte = new BLL.BLLTipoEmpresa();
            var btc = new BLLTipoContribuyente();
            //ViewData["TipoEmpresa"] = bte.All();
            ViewData["TipoContribuyente"] = btc.All();
            return View();
        }

        [Authorize]

        public ActionResult CreateProveedor()
        {
            var be = new BLLEmpresa();
            var bte = new BLL.BLLTipoEmpresa();
            var btc = new BLLTipoContribuyente();
            ViewData["TipoContribuyente"] = btc.All();
            ViewData["TipoEmpresa"] = bte.All();

            return View();
        }
        [Authorize]
        // POST: Empresa/Create
        [HttpPost]
        public ActionResult Create(Empresa cliente)
        {
            try
            {
                var user = User.Identity.Name;
                BLLEmpresa bllempresa = new BLLEmpresa();
                bllempresa.CreateCliente(cliente, user);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Empresa/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var btc = new BLLTipoContribuyente();
            ViewData["TipoContribuyente"] = btc.All();
            var cp = new BLLEmpresa();
            var empresa = cp.SelectByID(id);

            return View(empresa);
        }

        // POST: Empresa/Edit/5
        [Authorize]

        [HttpPost]
        public ActionResult Edit(int id, Empresa proveedor)
        {
            try
            {
                var btc = new BLLTipoContribuyente();
                ViewData["TipoContribuyente"] = btc.All();
                BLLEmpresa bllempresa = new BLLEmpresa();
                bllempresa.UpdateProveedor(proveedor);
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }

        // GET: Empresa/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Empresa/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Controllers/CobranzaController.cs
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;

namespace SIGT_TFI.Controllers
{
    public class CobranzaController : Controller
    {
        [Authorize]

        public ActionResult Create()
        {
            var btc = new BLLEntidadBancaria();
            ViewData["EntidadBancaria"] = btc.All();
            var btcomp = new BllMedioPago();
            ViewData["MedioPago"] = btcomp.All();
            var bllempresa = new BLLEmpresa();
            ViewData["Cliente"] = bllempresa.AllCliente();
            return View();
        }

        // GET: Cobranza/Create/Detalle
        [Authorize]
        public ActionResult CreateDetalle(Cobranza cobranza)
        {
            var btc = new BLLEntidadBancaria();
            ViewData["EntidadBancaria"] = btc.All();
            var btcomp = new BllMedioPago();
            ViewData["MedioPago"] = btcomp.All();
            var bllempresa = new BLLEmpresa();
            ViewData["Cliente"] = bllempresa.AllCliente();
            return View();
        }
        [Authorize]
        [HttpPost]
        // GET: Cobranza/Create/Detalle
        public ActionResult GenerarCobranza(FormCollection form)
        {
           
            
            var idmedios = form["IdMedioPago"].Split(new char[] { ',' }).Select(x => Convert.ToInt32(x)).ToList();
            var identidadbancarias = form["IdEntidadBancaria"].Split(new char[] { ',' }).Select(x => Convert.ToInt32(x)).ToList();
            var numerorecibos = form["NumeroRecibo"].Split(new char[] { ',' }).Select(x => Convert.ToInt32(x)).ToList();
            var fechas = form["FechaRecibo"].Split(new char[] { ',' }).Select(x => Convert.ToDateTime(x)).ToList();
            var plazos = form["PlazoRecibo"].Split(new char[] { ',' }).Select(x => Convert.ToInt32(x)).ToList();
            var endosables = form["Endosable"].Split(new char[] { ',' }).Select(x => Convert.ToBoolean(x)).ToList();
            var directos = form["Directo"].Split(new char[] { ',' }).Select(x => Convert.ToBoolean(x)).ToList();
            var docs = form["DocLibrador"].Split(new char[] { ',' }).Select(x => Convert.ToInt32(x)).ToList();
            var idcobranzas = form["idcobranza"].Split(new char[] { ',' }).Select(x => Convert.ToInt32(x)).ToList();
            var montos = form["Monto"].Split(new char[] { ',' }).Select(x => Convert.ToDouble(x)).ToList();
            var lista = new List<Recibo>();
            int len = idmedios.Count();
            for (int i = 0; i<len;i++)
            {
                lista.Add(new Recibo
                {
                    IdMedioPago = idmedios[i],
                    IdEntidadBancaria = identidadbancarias[i],
                    NumeroRecibo = numerorecibos[i],
                    FechaRecibo = fechas[i],
                    PlazoRecibo = plazos[i],
                    Endosable = endosables[i],
                    Directo = directos[i],
                    DocLibrador = docs[i],
                    idcobranza = idcobranzas[i],
                    Monto = montos[i],
                });

            }
            var bll = new BLLCobranza();
            var user = User.Identity.Name;

            bll.CrearCobranzaDetalle(lista,user);
                       

            return RedirectToAction("Create");
        }


        // POST: Cobranza/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Cobranza cobranza)
        {
            try
            {
                var bll = new BLLCobranza();
                var user = User.Identity.Name;

                bll.CrearCobranzaCabecera(cobranza, user);
                ViewBag.Mesagge = "lala";
                return RedirectToAction("CreateDetalle", new { id = cobranza.IdCobranzaCabecera });
            }
            catch
            {
                return View();
            }
        }

      

       

        
    }
}

SIGT-TFI/Controllers/FacturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BLL;
using Rotativa;
using SIGT_TFI.Models;

namespace SIGT_TFI.Controllers
{
    public class FacturaController : Controller
    {
        public static int GIdFactura;
        // GET: Factura
        public ActionResult Index()
        {
            
            return View();
        }
        [Authorize]
        public ActionResult Buscar()
        {
            var btc = new BLLTipoContribuyente();
            ViewData["TipoContribuyente"] = btc.All();
            var btcomp = new BLLTipoComprobante();
            ViewData["TipoComprobante"] = btcomp.All();
            var letra = new BLLLetra();
            ViewData["Letra"] = letra.All();
            var bllempresa = new BLLEmpresa();
            ViewData["Cliente"] = bllempresa.AllCliente();
            ViewData["ListaFacturas"] = null;
            return View();
        }

        [Authorize]
        public ActionResult BuscarComprobante()
        {
           
            var btcomp = new BLLTipoComprobante();
            ViewData["TipoComprobante"] = btcomp.All();
            var letra = new BLLLetra();
            ViewData["Letra"] = letra.All();
            var bllempresa = new BLLEmpresa();
            ViewData["Cliente"] = bllempresa.AllCliente();
            ViewData["ListaFacturas"] = null;
            return View();
        }


        [Authorize]
        [HttpPost]
        public ActionResult BuscarComprobante(Cliente factura)
        {

            var btcomp = new BLLTipoComprobante();
            ViewData["TipoComprobante"] = btcomp.All();
            var letra = new BLLLetra();
            ViewData["Letra"] = letra.All();
            var bllempresa = new BLLEmpresa();
            ViewData["Cliente"] = bllempresa.AllCliente();
            factura.IdTipo = 1;
            var fac = new BLLFactura();
            ViewData["ListaFacturas"] = fac.VW_FACTURA_CABECERA(factura).ToList();
            return View();
        }


        [Authorize]
        [HttpPost]
        public ActionResult Buscar(Cliente factura)
        {
            try
            {
                var btc = new BLLTipoContribuyente();
                ViewData["TipoContribuyente"] = btc.All();
                var btcomp = new BLLTipoComprobante();
                ViewData["TipoComprobante"] = btcomp.All();
                var letra = new BLLLetra();
                ViewData["Letra"] = letra.All();
                var bllempresa = new BLLEmpresa();
                ViewData["Cliente"] = bllempresa.AllCliente();
                var fac = new BLLFactura();
                ViewData["ListaTraslados"] = fac.LISTAR_COMPROBANTE_DETALLE(factura).ToList();
                
                return View(factura);
            }
            catch
            {
                return View();
            }
        }
        [Authorize]
        [HttpPost]
        public ActionResult GenerarFactura(FormCollection form)
        {
            string idtraslado = form["selected"];
            if (string.IsNullOrWhiteSpace(idtraslado)) throw new Exception("Debe seleccionar al menos un translado");
            var translations = idtraslado.Split(new char[] { ',' }).Select(x => Convert.ToInt32(x));
            var bll = new BLLFactura();
            var factura = new Cliente();
          
          
            factura.IdTipo = Convert.ToInt32(form["IdTipoComprobante"]);
            factura.IdLetra = Convert.ToInt32(form["IdLetra"]);
            factura.FechaFactura = Convert.ToDateTime(form["FechaFactura"]);
            factura.IdCliente = Convert.ToInt32(form["IdCliente"]);
            var user = User.Identity.Name;

            bll.CrearFactura(factura, user);
            var Lista = new System.Collections.ArrayList();
            Lista.Add(new Cliente());
            foreach (int value in translations)
            {
                factura.IdTraslado = value;
               
                bll.CrearFacturaDetalle(factura, user);
            }
            bll.CrearTotales(factura, user);

            return RedirectToAction("BuscarComprobante");
        }
        
        public ActionResult PDF(Cliente Factura)
        {
                 GIdFactura = Factura.id;
                 return new ActionAsPdf("PDF4") { FileName = "invoice" + GIdFactura + ".pdf" };
                //return Json(new { Result = "" }, JsonRequestBehavior.AllowGet);
       

        }
        
        public ActionResult PDF4()
        {
            var bll = new BLLFactura();
            var factura = new Cliente();
            var doc = bll.VW_FACTURA_HISTORICO2(GIdFactura);
            Models.FacturaPDFViewModels Vista = MapVista(doc);
            return View(Vista);

        }
        
        private FacturaPDFViewModels MapVista(List<Cliente> doc)
        {
            FacturaPDFViewModels model = new FacturaPDFViewModels();
            List<TrasladoPDFViewModels> listatraslado = new List<TrasladoPDFViewModels>();
            foreach (var item in doc)
            {
                model.Letra = item.Letra;
                model.Tipo = item.Tipo;
                model.NumeroFactura = item.NumeroFactura;
                model.FechaFactura = item.FechaFactura;
                model.Subtotal = item.Subtotal;
                model.Iva = item.Iva;
                model.Total = item.Total;
                model.Cuit = item.Cuit;
                model.RazonSocial = item.RazonSocial;
                model.Calle = item.Calle;
                model.numero = item.numero;
                model.Localidad = item.Localidad;
                model.TipoContribuyente = item.TipoContribuyente;
                TrasladoPDFViewModels traslados = new TrasladoPDFViewModels();
                traslados.NumeroTraslado = item.NumeroTraslado;
                traslados.carga = item.carga;
                traslados.Precio = item.Precio;
                traslados.Comision = item.Comision;
                traslados.PrecioTotal = item.Precio + item.Comision;
                traslados.PrecioxCant = (item.Precio + item.Comision) * (item.carga);
                listatraslado.Add(traslados);
                
                }
                     model.ListaTraslados = listatraslado;
                       return model;
                }
        }
    }

SIGT-TFI/Views/Shared/_Alerts.cshtml
@using BootstrapSupport
@if (TempData.ContainsKey(Alerts.ATTENTION))
{
    <div class="alert alert-block">
        <a class="close" data-dismiss="alert" href="#">x</a>
        <h4 class="alert-heading">Attention!</h4>
        @TempData[Alerts.ATTENTION]
    </div>
}
@foreach (string key in Alerts.ALL.Except(new[] { Alerts.ATTENTION }))
{
    if (TempData.ContainsKey(key))
    {
        <div class="alert alert-@key">
            <button type="button" class="close" data-dismiss="alert">x</button>
            @TempData[key]
        </div>
    }
}

SIGT-TFI/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

SIGT-TFI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SIGT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="~/Content/Login.css" rel="stylesheet" />
    @*<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link href="~/Content/selectize.default.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="~/Content/jquery.fancybox.css" rel="stylesheet" media="screen" />
    <script src="~/Scripts/jquery.fancybox.pack.js"></script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("SIGT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Proveedores", "Index", "Proveedor")</li>
                      </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>*@

    <!-- Añadirlo donde se quieren mostrar los mensajes de Bootstrap4 -->



    @if (TempData["ErrorNormal"] != null && TempData["ErrorNormal"] != String.Empty)
    {
        ViewBag.AlertError = TempData["ErrorNormal"];
    }
    @if (TempData["OKNormal"] != null && TempData["OKNormal"] != String.Empty)
    {
        ViewBag.AlertOK = TempData["OKNormal"];
    }


    @if (ViewBag.AlertError != null && ViewBag.AlertError != String.Empty)
    {
        @*
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">×</button>
                @ViewBag.AlertError
            </div>*@

        <input id="AlertError" type="hidden" value="@ViewBag.AlertError" />
    }

    @if (ViewBag.AlertOk != null && ViewBag.AlertOk != String.Empty)
    {

        @*<div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">×</button>
                @ViewBag.AlertOk
            </div>*@

        <input id="AlertOk" type="hidden" value="@ViewBag.AlertOK" />
    }
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid" id="nav">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">SIGT</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Home, "Index", "Home")</li>
                    <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Contact, "Contact", "Home")</li>
                    @*<li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Language, "Index", "Language")</li>*@
                    @*<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@SIGT_TFI.Resources.HomeTexts.Language<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Español", "Change", "Language", new { LanguageAbbrevation = "en" }, null)</li>
                <li>@Html.ActionLink("Ingles", "Change", "Language", new { LanguageAbbrevation = "fr" }, null)</li>
            </ul>
        </li>*@
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ABM <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Proveedores, "Index", "Proveedor")</li>
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Cliente, "Index", "Cliente")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@SIGT_TFI.Resources.HomeTexts.Traslado<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Listar, "Index", "Traslado")</li>
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Crear, "Create", "Traslado")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@SIGT_TFI.Resources.HomeTexts.Facturas<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Crear, "Buscar", "Factura")</li>
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Buscar, "BuscarComprobante", "Factura")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@SIGT_TFI.Resources.HomeTexts.Cobranza<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Agregar, "Create", "Cobranza")</li>
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.CuentaCorriente, "BuscarComprobantes", "CuentaCorriente")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@SIGT_TFI.Resources.HomeTexts.Precio<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @*<li>@Html.ActionLink("Lista de Precio", "Index", "ListaPrecio")</li>*@
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Agregar, "Buscar", "ListaPrecio")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@SIGT_TFI.Resources.HomeTexts.Sistema<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @*<li>@Html.ActionLink("Lista de Precio", "Index", "ListaPrecio")</li>*@
                                <li>@Html.ActionLink(SIGT_TFI.Resources.HomeTexts.Bitacora, "Index", "Bitacora")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                    }


                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.Partial("_LoginPartial")</li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SIGT - Federico Retta</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/selectize.min.js"></script>
    <script src="~/Scripts/jquery.fancybox.pack.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>