SIGT-TFI/Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BLL;

namespace SIGT_TFI.Controllers
{
    public class ContactoController : Controller
    {
        // GET: Contacto
        [Authorize]
        public ActionResult Index(int id)
        {
            var cp = new BLLContacto();
            var lista = cp.ListByCompanyID(id);
            var btc = new BLLTipoContacto();
            ViewData["TipoContacto"] = btc.All();
            //var transporte = new Transporte();
            //TempData["mydata"] = transporte.IdProveedor;
            return View(lista);
        }

        // GET: Contacto/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contacto/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            var btc = new BLLTipoContacto();
            ViewData["TipoContacto"] = btc.All();
            var contacto = new Contacto();
            contacto.idempresa = id;

            return View(contacto);
        }

        // POST: Contacto/Create
        [Authorize]

        [HttpPost]
        public ActionResult Create(Contacto contacto, int id)
        {

            BLLContacto bll = new BLLContacto();
            contacto.idempresa = id;
           contacto.id = 0;

            bll.CreateContacto(contacto);
            return RedirectToAction("Index", new { id = id });
        }

            // GET: Contacto/Edit/5
            public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Contacto/Edit/5
        [Authorize]

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Contacto/Delete/5
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Controllers/DomicilioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BLL;

namespace SIGT_TFI.Controllers
{
    public class DomicilioController : Controller
    {
        // GET: Domicilio
        [Authorize]
        public ActionResult Index(int id)
        {
            var cp = new BLLDomicilio();
            var lista = cp.ListByProviderID(id);

            var blllocalidad = new BLLLocalidad();
            ViewData["Localidad"] = blllocalidad.All();

            var bllprovincia = new BLLProvincia();
            ViewData["Provincia"] = bllprovincia.All();
            
            return View(lista);
        }

        // GET: Domicilio/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Domicilio/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            var blllocalidad = new BLLLocalidad();
            ViewData["Localidad"] = blllocalidad.All();

            var bllprovincia = new BLLProvincia();
            ViewData["Provincia"] = bllprovincia.All();
            var domicilio = new Domicilio();
            domicilio.Idempresa = id;

            return View(domicilio);
        }

        // POST: Domicilio/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Domicilio domicilio, int id)
        {
            try
            {

                BLLDomicilio bll = new BLLDomicilio();
                domicilio.Idempresa = id;
                domicilio.Id = 0;

                bll.CreateDomicilio(domicilio);
                return RedirectToAction("Index", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Domicilio/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Domicilio/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Domicilio/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Domicilio/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BLL;
using PagedList;
using PagedList.Mvc;

namespace SIGT_TFI.Controllers
{
    public class ProveedorController : Controller
    {
        [Authorize]
        // GET: Empresa
        public ActionResult Index(string search, int ? page)
        {
            var cp = new BLLEmpresa();
            var lista = cp.AllProveedor();
            var btc = new BLLTipoContribuyente();
            ViewData["TipoContribuyente"] = btc.All();
            if (search == null) search = "";
            return View(lista.Where(x => x.RazonSocial.ToUpper().StartsWith(search.ToUpper())).ToList().ToPagedList(page ?? 1, 10));
           
        }

        // GET: Empresa/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Empresa/Create
        [Authorize]
        public ActionResult Create()
        {
            var be = new BLLEmpresa();
            var bte = new BLL.BLLTipoEmpresa();
            var btc = new BLLTipoContribuyente();
            ViewData["TipoEmpresa"] = bte.All();
            ViewData["TipoContribuyente"] = btc.All();
             return View();
        }

        // GET: Cliente/Create
        [Authorize]
        public ActionResult CreateProveedor()
        {
            var be = new BLLEmpresa();
            var bte = new BLL.BLLTipoEmpresa();
            var btc = new BLLTipoContribuyente();
            ViewData["TipoContribuyente"] = btc.All();
            ViewData["TipoEmpresa"] = bte.All();
            
            return View();
        }

        // POST: Empresa/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(Empresa proveedor)
        {
            try
            {
                var user = User.Identity.Name;

                BLLEmpresa bllempresa = new BLLEmpresa();
                bllempresa.CreateProveedor(proveedor, user);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Empresa/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var btc = new BLLTipoContribuyente();
            ViewData["TipoContribuyente"] = btc.All();
            var cp = new BLLEmpresa();
            var empresa = cp.SelectByID(id);

            return View(empresa);
        }

        // POST: Empresa/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit(int id, Empresa proveedor)
        {
            try
            {
                var btc = new BLLTipoContribuyente();
                ViewData["TipoContribuyente"] = btc.All();
                BLLEmpresa bllempresa = new BLLEmpresa();
                bllempresa.UpdateProveedor(proveedor);
                return RedirectToAction("Index");
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Empresa/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Empresa/Delete/5
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Controllers/TransporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Entities;

namespace SIGT_TFI.Controllers
{
    public class TransporteController : Controller
    {
        // GET: Transporte
        [Authorize]
        public ActionResult Index(int id)
        {
            var cp = new BLL.BLLTransporte();
            var lista = cp.ListByProviderID(id);
            var transporte = new Transporte();
            TempData["mydata"] = transporte.IdProveedor;
            return View(lista);
        }

        // GET: Transporte/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Transporte/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            var blltipocontacto = new BLLTipoContacto();
            ViewData["TipoContacto"] = blltipocontacto.All();
            var tranp = new Transporte();
            tranp.IdProveedor = id;

            return View(tranp);
        }

        // POST: Transporte/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Transporte transporte, int id)
        {
          
            BLLTransporte blltransporte = new BLLTransporte();
            transporte.IdProveedor = id;
            

            blltransporte.CreateProveedor(transporte);
                return RedirectToAction("Index", new { id = id });
          
          
        }

        // GET: Transporte/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Transporte/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Transporte/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Transporte/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SIGT-TFI/Views/Proveedor/Create.cshtml
@model Entities.Empresa

@{
    ViewBag.Title = "Create";
}
@{ var listadoTipoContribuyente = new List<SelectListItem>();
    foreach (var std in ViewData["TipoContribuyente"] as IList<Entities.TipoContribuyente>)
    {
        var elemento = new SelectListItem()
        {
            Text = std.nombre,
            Value = std.id.ToString()
        };
        listadoTipoContribuyente.Add(elemento);
    }
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <h4>@SIGT_TFI.Resources.HomeTexts.Crear @SIGT_TFI.Resources.HomeTexts.Proveedores</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, @SIGT_TFI.Resources.HomeTexts.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreFantasia, @SIGT_TFI.Resources.HomeTexts.Nombrefantasia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreFantasia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreFantasia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuit, @SIGT_TFI.Resources.HomeTexts.Cuit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo_Contribuyente, @SIGT_TFI.Resources.HomeTexts.TipoContribuyente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Tipo_Contribuyente", listadoTipoContribuyente, new { @class = "form-control dropdown-toggle" })
                @Html.ValidationMessageFor(model => model.Tipo_Contribuyente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@SIGT_TFI.Resources.HomeTexts.Agregar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SIGT-TFI/Views/Proveedor/Details.cshtml
@model Entities.Empresa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RazonSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RazonSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreFantasia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreFantasia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Contribuyente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Contribuyente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_Empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_Empresa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SIGT-TFI/Views/Proveedor/Edit.cshtml
@model Entities.Empresa
@using Entities

@{
    ViewBag.Title = "Edit";
}
@{ var listadoTipoContribuyente = new List<SelectListItem>();
    foreach (var std in ViewData["TipoContribuyente"] as IList<Entities.TipoContribuyente>)
    {
        var elemento = new SelectListItem()
        {
            Text = std.nombre,
            Value = std.id.ToString()
        };
        listadoTipoContribuyente.Add(elemento);
    }
}

<h2>Editar Proveedor</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empresa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreFantasia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreFantasia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreFantasia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo_Contribuyente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Tipo_Contribuyente", listadoTipoContribuyente, new { @class = "form-control dropdown-toggle" })
                @Html.ValidationMessageFor(model => model.Tipo_Contribuyente, "", new { @class = "text-danger" })
            </div>
        </div>
      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SIGT-TFI/Views/Proveedor/Index.cshtml
@model IPagedList<Entities.Empresa>
@using PagedList;
@using PagedList.Mvc;
@using Entities;
@{
    ViewBag.Title = "Index";
    var tipocontri = "TipoContribuyente";
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<h2>@SIGT_TFI.Resources.HomeTexts.Proveedores</h2> 
<br />

<p>
    @Html.ActionLink(@SIGT_TFI.Resources.HomeTexts.Crear, "Create", null, new { @class = "btn btn-primary" })
</p>
<p>
    @using (Html.BeginForm("Index","Proveedor", FormMethod.Get)) {
    <b>@SIGT_TFI.Resources.HomeTexts.BuscarPor:</b>
    @Html.TextBox("Search") <input type="submit" value="@SIGT_TFI.Resources.HomeTexts.Buscar" class="btn btn-primary" />
    }
</p>
<table class="table table-striped">
    <tr>
        <th>
            @SIGT_TFI.Resources.HomeTexts.RazonSocial
        </th>
        <th>
            @SIGT_TFI.Resources.HomeTexts.Nombrefantasia
        </th>
        <th>
            @SIGT_TFI.Resources.HomeTexts.Cuit
        </th>
        <th>
            @SIGT_TFI.Resources.HomeTexts.TipoContribuyente
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    {
        foreach (var std in ViewData["TipoContribuyente"] as IList<TipoContribuyente>)
        {
            if (std.id == item.Tipo_Contribuyente)
            {
                tipocontri = std.nombre;
                break;
            }
        }
    }
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RazonSocial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NombreFantasia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cuit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => tipocontri)
        </td>
       
        <td>
            @*<a href="@Url.Action("Edit", "Proveedor", new { id = item.id })" data-toggle="tooltip" data-placement="top" title="Editar!">
                <span class="far fa-edit"></span>
            </a>|
            <a href="@Url.Action("Details", "Detalles", new { id = item.id })" data-toggle="tooltip" data-placement="top" title="Detalles!">
            <span class="glyphicon glyphicon-search">
                </span>
                </a>|*@
            <a href="@Url.Action("Index", "Transporte", new { id = item.id })" data-toggle="tooltip" data-placement="top" title="@SIGT_TFI.Resources.HomeTexts.Transporte">
                <span class="fas fa-truck"></span>
            </a>|
            <a href="@Url.Action("Index", "Contacto", new { id = item.id })" data-toggle="tooltip" data-placement="top" title="@SIGT_TFI.Resources.HomeTexts.Contactos">
                <span class="far fa-envelope-open"></span>
            </a>
            |
            <a href="@Url.Action("Index", "Domicilio", new { id = item.id })" data-toggle="tooltip" data-placement="top" title="@SIGT_TFI.Resources.HomeTexts.Domicilio">
                <span class="far fa-address-book"></span>
            </a>

        </td>
    </tr>
}

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

}